# Generated by Django 5.0.2 on 2024-02-07 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_1', models.PositiveIntegerField(default=0)),
                ('winner_2', models.PositiveIntegerField(default=0)),
                ('tie', models.PositiveIntegerField(default=0)),
                ('rounds', models.PositiveIntegerField(default=1)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_as_user_1', to='users.usermodel')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_as_user_2', to='users.usermodel')),
            ],
        ),
    ]
