# Generated by Django 5.0.2 on 2024-02-07 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fightmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightmodel',
            name='grand_winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usermodel'),
        ),
        migrations.AddField(
            model_name='fightmodel',
            name='status',
            field=models.CharField(choices=[('start', 'Start'), ('finish', 'Finish')], default='start', max_length=10),
        ),
    ]
